Name = "Selectel"
Description = ''''''
URL = "https://docs.selectel.ru/en/"
Code = "selectelv2"
Since = "v4.16.2"

Example = '''
SELECTEL_USERNAME=trex \
SELECTEL_PASSWORD=xxxxx \
SELECTEL_ACCOUNT_ID=1234567 \
SELECTEL_PROJECT_ID=111a11111aaa11aa1a11aaa11111aa1a \
lego --email you@example.com --dns selectelv2 --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    SELECTEL_USERNAME = "Openstack username"
    SELECTEL_PASSWORD = "Openstack username's password"
    SELECTEL_ACCOUNT_ID = "Selectel account ID (INT)"
    SELECTEL_PROJECT_ID = "Cloud project ID (UUID)"
  [Configuration.Additional]
    SELECTEL_BASE_URL = "API endpoint URL"
    SELECTEL_POLLING_INTERVAL = "Time between DNS propagation check"
    SELECTEL_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    SELECTEL_TTL = "The TTL of the TXT record used for the DNS challenge"
    SELECTEL_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://developers.selectel.ru/docs/cloud-services/dns_api/dns_api_actual/"